apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19seir-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid19seir
  template:
    metadata:
      labels:
        app: covid19seir
    spec:
      containers:
      - name: covid19seir
        image: ducovid19tools/covid19seir:v0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: covid19seir-service
spec:
  ports:
  - port: 3838
    targetPort: 3838
    protocol: TCP
  selector:
    app: covid19seir
