apiVersion: apps/v1
kind: Deployment
metadata:
  name: complexit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complexit
  template:
    metadata:
      labels:
        app: complexit
    spec:
      containers:
      - name: complexit
        image: ducovid19tools/complexit:v0.1.1
---
apiVersion: v1
kind: Service
metadata:
  name: complexit-service
spec:
  ports:
  - port: 3838
    targetPort: 3838
    protocol: TCP
  selector:
    app: complexit
