apiVersion: apps/v1
kind: Deployment
metadata:
  name: complexit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complexit
  template:
    metadata:
      labels:
        app: complexit
    spec:
      containers:
      - name: complexit
        image: ducovid19tools/complexit@sha256:07b0670b6ed8a7a48bef61ece3de7f8de5b608000ba6d6f8875ae11db6a850eb
---
apiVersion: v1
kind: Service
metadata:
  name: complexit-service
spec:
  ports:
  - port: 3838
    targetPort: 3838
    protocol: TCP
  selector:
    app: complexit
