apiVersion: apps/v1
kind: Deployment
metadata:
  name: complexit-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: complexit
  template:
    metadata:
      labels:
        app: complexit
    spec:
      containers:
      - name: complexit
        image: alisonrclarke/complex-it@sha256:d8de22adad8628f8dde490f16c3b727c300997bd496cf5ac5c369b5352c1a3c9
---
apiVersion: v1
kind: Service
metadata:
  name: complexit-service
spec:
  ports:
  - port: 3838
    targetPort: 3838
    protocol: TCP
  selector:
    app: complexit
